In [76]:
import pandas as pd
import numpy as np
df = pd.read_csv('raw_data.csv')

In [22]:
df.head()

,Unnamed: 0,hotel_name,review,address,prices
0,0,1. The Papandayan,5.0,"Jl. Gatot Subroto 83, Bandung 40262 Indonesia",752086
1,1,2. The Gaia Hotel Bandung,5.0,"No. 430 Jl. Dr. Setiabudi, Bandung 40143 Indon...",1640356
2,2,3. Janevalla Bandung,4.5,"Jalan Aceh No. 65, Jawa Barat, Bandung 40115 I...",862921
3,3,4. Grand Tjokro Premiere Bandung,4.5,"Jl. Cihampelas no. 211-217, Bandung 40131 Indo...",489988
4,4,5. Swiss-Belresort Dago Heritage,5.0,Lapangan Golf Dago Atas No. 78 Dago Heritage G...,939250

In [77]:
def splitting(s):
  s['hotel_name'] = s['hotel_name'].split('.')[1]
  return s

df = df[df.hotel_name != 'None']
df = df[df.review != '0.0']
df = df[df.address != 'None']
df = df[df.prices != 0]
df.drop(df.columns[df.columns.str.contains('unnamed',case = False)],axis = 1, inplace = True)
df = df.apply(splitting , axis = 1)
print(df)
df.to_csv('data_cleansed.csv', index=False)

                        hotel_name  review  \
0                   The Papandayan     5.0
1           The Gaia Hotel Bandung     5.0
2                Janevalla Bandung     4.5
3    Grand Tjokro Premiere Bandung     4.5
4    Swiss-Belresort Dago Heritage     5.0
..                             ...     ...
85                     HAY Bandung     4.0
86                 De Batara Hotel     3.5
87      Grand Aquila Hotel Bandung     3.5
88              Green Batara Hotel     3.5
89               Vio Hotel Pasteur     3.5

                                              address   prices
0       Jl. Gatot Subroto 83, Bandung 40262 Indonesia   752086
1   No. 430 Jl. Dr. Setiabudi, Bandung 40143 Indon...  1640356
2   Jalan Aceh No. 65, Jawa Barat, Bandung 40115 I...   862921
3   Jl. Cihampelas no. 211-217, Bandung 40131 Indo...   489988
4   Lapangan Golf Dago Atas No. 78 Dago Heritage G...   939250
..                                                ...      ...
85      Jl. Trunojoyo no. 19, Bandung 40115 Indonesia   518513
86    Jl. Cihampelas no. 112, Bandung 40116 Indonesia   227878
87     Jl. DR Djundjunan 116, Bandung 40163 Indonesia   685736
88    Jln. Cihampelas no 145, Bandung 40131 Indonesia   232754
89  Jl. Dr Jungjunan no. 154 Pasteur, Bandung 4016...   367859

[88 rows x 4 columns]